name: build-and-test

on:
  pull_request:
    branches: master
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      - ACTIONS_RUNNER_DEBUG

    steps:
      - uses: actions/checkout@v2
        # Pull the entire branch and not just the single commit
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - run: |
          echo action_runner_debug - "${ACTIONS_RUNNER_DEBUG}"
