name: build-and-test

on:
  pull_request:
    branches: master
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build-and-test:
    # skip if the PR is a draft or if it has a WIP label or it has a test-results-out-of-date label
    if: github.event.pull_request.draft == false || ( github.event.pull_request.draft && contains( github.event.pull_request.labels.*.name, 'run-CI'))
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        # Pull the entire branch and not just the single commit
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - run: |
          MSG=$(git log --format=%B -n 1 ${{github.event.after}})
          echo "::set-env name=COMMIT_MESSAGE::${MSG}"