name: build-and-test

on:
  pull_request:
    branches: master
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo action_runner_debug - $ACTIONS_RUNNER_DEBUG
          exit 1
