name: build-and-test

on:
  pull_request:
    branches: master
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: nbaztec/add-pr-review-comment@v1
        with:
          message: |
            [{"path":".github/workflows/test-triggers.yml","line":10,"text":"something was deleted","side":"RIGHT"}]
          repo-token-user-login: "github-actions[bot]" # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
